apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: global-parameters-
  namespace: argo
spec:
  entrypoint: B
  arguments:
    parameters:
    - name: log-level
      value: INFO

  templates:
  - name: A
    container:
      image: tapa4ik/log-generator
      env:
      - name: LOG_LEVEL
        value: "{{workflow.parameters.log-level}}"

  - name: B
    container:
      image: micheliac/log-generator
      env:
      - name: LOG_LEVEL
        value: "{{workflow.parameters.log-level}}"

