# kubectl create secret generic git-creds --from-literal=username=xxxx --from-literal=password=xxx
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    container:
      volumeMounts:
        - mountPath: /git/argoproj
          name: argoproj
        - mountPath: /secret
          name: git-creds
        - mountPath: git-creds
          name: known-hosts
    volumes:
      - name: argoproj
        emptyDir: {}
      - name: git-creds
        secret:
          secretName: git-creds
      # The name of the key in the secret must be "ssh_known_hosts"
      # Make sure you have your git provider added in the known hosts
      # e.g. create the secret by running, kubectl -n argo-events create secret generic git-known-hosts --from-file=ssh_known_hosts=.ssh/known_hosts
#      - name: known-hosts
#        secret:
#          secretName: git-known-hosts
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          operation: create
          source:
            git:
              url: "https://github.com/argoproj/argo-workflows.git"
              cloneDirectory: "/git/argoproj"
              git-creds: "/secret/git-creds"
              namespace: argo-events
              filePath: "examples/hello-world.yaml"
              branch: "master"
            credentials:
              secret:
                name: git-creds
                key: username
              secret:
                name: git-creds
                key: password
