apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          operation: create
          source:
            s3:
              bucket:
                name: workflows2024
                key: hello-world.yaml
              endpoint: "https://workflows2024.s3.eu-central-1.amazonaws.com"
              insecure: true
              accessKey:
                key: accesskey
                name: aws
                namespace: argo-events
              secretKey:
                key: secretkey
                name: aws
                namespace: argo-events
